### ISSUE TITLE
INTERPROCEDURAL_OPTIMIZATION can cause `/usr/bin/ld: libJolt.a: error adding symbols: file format not recognized`

### ISSUE THREAD

**Issue by tksuoran** [jrouwe/JoltPhysics#418] opened 2023-01-24 14:41 UTC
I noticed that `INTERPROCEDURAL_OPTIMIZATION` has been turned on by default.

This can make it slightly more difficult to make a release build with clang: Gnu binutils linker cannot always parse clang output when lto is used.

Installing lld and adding `-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld -DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld` to cmake configure may help.

I use Jolt via cmake fetch content.

**Comment by tksuoran** [comment] 2023-01-24 17:10
I am seeing this on both Ubuntu 20.04 based arm64 system with clang-12 and Ubuntu 22.10 based x64 system with clang-15. The later one has
```
$ clang-15 --version
Ubuntu clang version 15.0.2-1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.39
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by jrouwe** [comment] 2023-01-28 16:03
Hello,

I've been playing around with CMake FetchContent a bit (see https://github.com/jrouwe/JoltPhysicsHelloWorld) and I can reproduce your error on Ubuntu 22.04 using clang 14 as well.

The reason why it seems to fail is that Jolt's CMakeLists.txt turns on link time optimization using the check_ipo_supported macro, but only for the Jolt library and not for any applications that use it. If you don't repeat the same code in your own CMakeLists.txt:

```
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE OFF)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_DISTRIBUTION OFF)

# On ARM, whole program optimization triggers an internal compiler error during code gen, so we don't turn it on
if (INTERPROCEDURAL_OPTIMIZATION AND NOT ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "ARM64") AND NOT ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "ARM"))
	include(CheckIPOSupported)
	check_ipo_supported(RESULT IS_IPO_SUPPORTED OUTPUT IPO_CHECK_OUTPUT)

	if (IS_IPO_SUPPORTED)
		set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
		set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_DISTRIBUTION ON)
	else()
		message(WARNING "Interprocedural optimizations are not supported: ${IPO_CHECK_OUTPUT}")
	endif()
endif()
```

Then the application doesn't compile:

```
/usr/bin/ld: _deps/joltphysics-build/libJolt.a: error adding symbols: file format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/HelloWorld.dir/build.make:98: HelloWorld] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/HelloWorld.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

If you don't want link time optimizations you can also use:

```
set(INTERPROCEDURAL_OPTIMIZATION OFF)
```

before calling FetchContent_MakeAvailable.

I'm not a big expert on clang and link time optimizations, so I don't know why clang doesn't throw a more user friendly error / is able to ignore the setting. Maybe @mihe knows more about this.

In any case you can reproduce it in the JoltPhysicsHelloWorld sample by removing [this block](https://github.com/jrouwe/JoltPhysicsHelloWorld/blob/1083a258b9f9881226e2d2cda78b73f365dc671a/Build/CMakeLists.txt#L215-L229) of code and compiling on Linux in Release mode.

**Comment by jrouwe** [comment] 2023-01-30 21:58
Thanks for the investigations! I'm still pondering what the best option is.

**Comment by jrouwe** [comment] 2023-01-30 22:53
Ok, I went for 5, documenting the error (in 3 places!). I think it is quite easy to disable LTO by doing ```set(INTERPROCEDURAL_OPTIMIZATION OFF)``` before doing FetchContent if you don't want LTO and I'd prefer not to silently lose 10% performance.

@tksuoran is this acceptable?

**Comment by tksuoran** [comment] 2023-01-31 06:27
Yes, I think it is good. Thanks!

**Comment by jrouwe** [comment] 2023-01-31 20:47
Thanks both for your help! I have a feeling that this is going to come back at some point but for now I'm closing the ticket.

**Closed by jrouwe** 2023-01-31 20:47 UTC
