### ISSUE TITLE
ARMv7 and package manager support (xrepo)

### ISSUE THREAD

**Issue by SirLynix** [jrouwe/JoltPhysics#494] opened 2023-04-06 11:02 UTC
Hi.

I added Jolt Physics to xmake-repo, a package manager for C++ (see https://github.com/xmake-io/xmake-repo/pull/1685).

[XMake](https://xmake.io) is a build system (like CMake) which is able to use other build systems, for example the [Bullet script](https://github.com/xmake-io/xmake-repo/blob/master/packages/b/bullet3/xmake.lua#L25) directly triggers cmake and then xmake retrieves the built includes/binaries.

I tried to integrate Jolt the same way but this was a bit complicated for multiple reasons, one of them is that Jolt CMakeLists forces MSVC runtime library.

```cmake
	# Set runtime library
	if (USE_STATIC_MSVC_RUNTIME_LIBRARY)
		set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
	else()
		set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
	endif()
```

XMake allows one to build a debug application with release packages (which is useful to debug app without having all dependencies without optimization), but since runtime library "must" match across binaries it allows to compile dependencies in release with a debug runtime.

For example, when I'm debugging my engine, I'm using a debug runtime (MDd) but my dependencies are still compiled in release (to keep optimization active on them, Assimp is really slow in debug mode) with the MDd runtime (since Jolt is statically linked, it has to match).

I had other issues with platform detection, so instead of patching the CMakeLists I decided to rewrite the build script for xmake: https://github.com/xmake-io/xmake-repo/blob/master/packages/j/joltphysics/port/xmake.lua

This is only to give a bit of context and to tell you that Jolt is available on another package manager/build system.

Now, that build script works well for Windows/Linux/macOS/iOS/emscripten and Android (ARMv8-a only) but it [fails on some platforms](https://github.com/SirLynix/xmake-repo/pull/6):

- [Windows ARM64 using Visual Studio 2019](https://github.com/SirLynix/xmake-repo/actions/runs/4448172888/jobs/7810631455?pr=6#step:5:44) (some intrinsics were not available for ARM64 before VS2022, mostly don't care).
- [Android ARMv7](https://github.com/SirLynix/xmake-repo/actions/runs/4448172922/jobs/7810630422?pr=6#step:5:163)
- [musl (aarch64)](https://github.com/SirLynix/xmake-repo/actions/runs/4448172892/jobs/7810628251?pr=6#step:5:41)
- [FreeBSD](https://github.com/SirLynix/xmake-repo/actions/runs/4448172894/jobs/7810629860?pr=6#step:3:4289)

I think this can be quite easily fixed by disabling some optimizations on those platforms, better have a slower Jolt than no Jolt at all I suppose.

Also, a nice feature Bullet has is that it's able to detect the CPU instruction set on launch and make use of SSE4.2 (for example) when available (see [void btSequentialImpulseConstraintSolver::setupSolverFunctions(bool useSimd)](https://github.com/bulletphysics/bullet3/blob/0e59474e1cf1fd69e3ca512826cfbe15cd6a9cec/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp#L360-L361)), would something similar be possible with Jolt?

**Comment by jrouwe** [comment] 2023-04-07 15:13
Hello,

> I tried to integrate Jolt the same way but this was a bit complicated for multiple reasons, one of them is that Jolt CMakeLists forces MSVC runtime library.

If you have suggestions on how to do this better then please let me know.

> I think this can be quite easily fixed by disabling some optimizations on those platforms, better have a slower Jolt than no Jolt at all I suppose.

Jolt already compiles on ARMv7 with MSVC and it has a plain C++ fallback for almost all functionality so I think making stuff compile should not be very hard. If you want to help out with this then that would be appreciated. The tricky thing is going to be to find a good set of defines to control all of this, so if you need new defines then please discuss first.

> Also, a nice feature Bullet has is that it's able to detect the CPU instruction set on launch and make use of SSE4.2 (for example) when available.

This has been asked before, please check the following issue for my answer: https://github.com/jrouwe/JoltPhysics/issues/350

**Comment by SirLynix** [comment] 2023-04-08 11:39
> If you have suggestions on how to do this better then please let me know.

Either only set `CMAKE_MSVC_RUNTIME_LIBRARY` when `USE_STATIC_MSVC_RUNTIME_LIBRARY` is ON (and leave the default value, this is what some libs do, like Assimp) or don't touch `CMAKE_MSVC_RUNTIME_LIBRARY` at all and let people configure it from cmake directly.

fyi, `CMAKE_MSVC_RUNTIME_LIBRARY` already defaults to `MultiThreaded$<$<CONFIG:Debug>:Debug>DLL` (https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html#prop_tgt:MSVC_RUNTIME_LIBRARY) so setting it only prevents user configuration.

> Jolt already compiles on ARMv7 with MSVC and it has a plain C++ fallback for almost all functionality so I think making stuff compile should not be very hard. If you want to help out with this then that would be appreciated. The tricky thing is going to be to find a good set of defines to control all of this, so if you need new defines then please discuss first.

I don't have a lot of time right now but I'll try to improve that to make it compile on all platforms supported by xmake (all mainstream ones).

> This has been asked before, please check the following issue for my answer: https://github.com/jrouwe/JoltPhysics/issues/350

Fair enough, I understand. I think I'll stick to SSE2 for now and run some benchmarks later.

By the way, is there any plan to support Jolt compilation as a dynamic library? I'm not sure this is possible due to the use of global that have to be set in the user code (globals aren't shared across DLLs).

**Comment by mihe** [comment] 2023-04-08 12:46
I took the liberty of making a PR for the issue with `CMAKE_MSVC_RUNTIME_LIBRARY` in #496.

In my experience omitting this variable entirely is a bit of a rabbit hole due to how generator expressions are evaluated, which makes using a static runtime cumbersome when coupled with multi-configuration generators like Visual Studio, so I took the route of removing the redundant `set` when `USE_STATIC_MSVC_RUNTIME_LIBRARY` is `OFF`.

**Comment by jrouwe** [comment] 2023-04-08 18:32
The PR has been merged. Thanks!

> is there any plan to support Jolt compilation as a dynamic library?

No there are no plans for that. If you need this I would suggest looking at one of the 2 C wrappers mentioned on the main page. They both create a DLL and define an API that is more DLL friendly.

**Comment by jrouwe** [comment] 2023-04-08 20:20
Looking quickly at the failing platforms:

* ARM & MSVC2019 - That was an easy fix, see #497.
* Android ARM v7 - I tried this as well (see https://github.com/jrouwe/JoltPhysics/tree/features/android_armv7a) and it compiles but then I realized that I have no way of verifying that it runs. I don't think an armv8 Android device can run the armv7 code (when I remove the armv8 code then Android Studio just grays out the run button).
* musl/FreeBSD - This will take me too much time, so unless someone creates a PR I won't support it.

**Comment by SirLynix** [comment] 2023-04-09 17:38
I can confirm that VS2019+ARM and Android/ARMv7 are fixed, or at least compile.

I will now try to use cmake to compile Jolt instead of xmake in the package script, to prevent having to maintain two build scripts.

**Comment by SirLynix** [comment] 2023-04-09 18:17
I updated it but face now two issues (<https://github.com/SirLynix/xmake-repo/pull/6>):
- `-Werror`/`/WX` cannot be disabled and there are warnings on some platforms ([example](https://github.com/SirLynix/xmake-repo/actions/runs/4651786873/jobs/8231601347?pr=6))
- The CMake lacks installation directive and neithers headers not binaries are copied to the output folder.

**Comment by jrouwe** [comment] 2023-04-09 19:30
> -Werror//WX cannot be disabled and there are warnings on some platforms ([example](https://github.com/SirLynix/xmake-repo/actions/runs/4651786873/jobs/8231601347?pr=6))

I could add an option for that but personally I would prefer to keep warnings as errors (I hate code that produces a lot of warnings during compilation). I tried reproducing the warning on VS2019 but it doesn't happen for me. Did you add some other config flags that triggers this?

My guess is that in Core.h after line 207 we need to add:

```
JPH_MSVC2019_SUPPRESS_WARNING(4738)
```

as the warning itself doesn't seem very useful. But since I can't reproduce the warning I can't verify that that fixes it either.

Can you maybe send me the command line flags that are passed to cl.exe?

> The CMake lacks installation directive and neithers headers not binaries are copied to the output folder.

I'm not a big fan of installing a library to a system lib folder. I think that means that if a project uses a newer version of the library in a local folder it may accidentally read the header from an older version that resides in the system folder. Is this really needed for xmake to work (for cmake you just download and compile a local version using cmake fetch content, no installation needed)?

**Comment by SirLynix** [comment] 2023-04-10 08:41
> I could add an option for that but personally I would prefer to keep warnings as errors (I hate code that produces a lot of warnings during compilation)

I totally understand this point of view, however for a package manager this will cause issues as you cannot predict which compiler version will be used and don't want the package installation to fail because a compiler update added a warning (or even bugged a warning, this happens unfortunately).

If you don't want to add an option for this, I can patch the CMakeLists.txt from the package script before running CMake, but this is less reliable.

> Can you maybe send me the command line flags that are passed to cl.exe?

[Here you are](https://github.com/SirLynix/xmake-repo/actions/runs/4655926354/jobs/8239053119#step:5:297)

> I'm not a big fan of installing a library to a system lib folder. I think that means that if a project uses a newer version of the library in a local folder it may accidentally read the header from an older version that resides in the system folder. Is this really needed for xmake to work (for cmake you just download and compile a local version using cmake fetch content, no installation needed)?

xmake directs cmake to install files to a temporary folder from where it then copies include/lib to one of its own folder (something like %localappdata%/.xmake/packages/j/joltphysics/...), nothing is installed to the system, but this requires CMake installation directives.

Another option is to manually copy files from the script package, but again this is less reliable as it will need to be updated if you make changes (new headers/folders/etc.)

**Comment by jrouwe** [comment] 2023-04-10 13:07
I wasn't able to reproduce the warning with the options you sent but I made a cmake option to turn warnings off.

I also added an install target.

**Comment by jrouwe** [comment] 2023-04-10 14:47
Ok, I was planning to release a new version soon.

B.t.w. I merged the armv7 support into the main branch so you probably need to update your script.

**Comment by jrouwe** [comment] 2023-04-14 14:23
I just created release v3.0.0

**Closed by jrouwe** 2023-04-14 14:23 UTC

**Comment by SirLynix** [comment] 2023-04-15 08:25
I submitted a PR to xmake-repo: https://github.com/xmake-io/xmake-repo/pull/1987
