### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by amerkoleci** [jrouwe/JoltPhysics#298] opened 2022-10-24 11:42 UTC
Hi,
I'm trying to add ARM64 support for my C# bindings (Windows and MacOS), but MacOS fails when I compile for ARM64.

Any thought?

Those are the CMake args I used:

https://github.com/amerkoleci/JoltPhysicsSharp/blob/main/build.cake#L32

**Comment by jrouwe** [comment] 2022-10-24 12:24
It looks like your errors are:

```
clang: error: argument unused during compilation: '-msse4.2' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-mpopcnt' [-Werror,-Wunused-command-line-argument]
```

And it's probably caused because you're cross compiling from x86 to ARM. I only tested compiling on MacOS ARM for ARM and MacOS x86 for x86. 

The issue is probably in:

https://github.com/jrouwe/JoltPhysics/blob/master/Build/CMakeLists.txt#L151

where it checks if the target platform is x86:

```
elseif ("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64" OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "AMD64")
```

and adds the x86 specific compiler options if it is. Unfortunately the [CMAKE_SYSTEM_PROCESSOR](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html) variable is not consistent [according to this](https://stackoverflow.com/questions/11944060/how-to-detect-target-architecture-using-cmake).

I don't own a Mac so testing is a bit hard for me. What you can do is add a:

```
message("CMAKE_SYSTEM_PROCESSOR ${CMAKE_SYSTEM_PROCESSOR}")
message("CMAKE_OSX_ARCHITECTURES ${CMAKE_OSX_ARCHITECTURES}")
```

before that if block to see what the value is set to. If CMAKE_OSX_ARCHITECTURES provides the right platform name on Mac, you could perhaps extend the 'if' so that it takes the ARM branch instead of the x86 branch (and if you do fix it please send a pull request).

**Comment by amerkoleci** [comment] 2022-10-24 12:36
I think thats the Linux part, the MacOS compiler probably end here:

https://github.com/jrouwe/JoltPhysics/blob/master/Build/CMakeLists.txt#L113

**Comment by amerkoleci** [comment] 2022-10-24 13:16
Ok,
I managed to FIX it with this commit: https://github.com/amerkoleci/JoltPhysicsSharp/commit/6c4de32f623bb50ee6e61e75ebf5ac8c85753655

I check the CMAKE_OSX_ARCHITECTURES arm64 presence.

I'll try to FIX Windows ARM64 build as well:

```
cmake -B ".\build\win_arm64" -S "." -G "Visual Studio 17 2022" -A ARM64
```

**Comment by jrouwe** [comment] 2022-11-04 12:44
Are you still working on making ARM work on Windows? I'm going to take a look at your changes right now and will try to get things to work.

**Comment by amerkoleci** [comment] 2022-11-04 12:46
Ok,
ping me if you need any help :)

**Comment by jrouwe** [comment] 2022-11-04 16:12
I created #317. 

I was not quite sure why the check for _M_HYBRID_X86_ARM64 and _M_ARM64EC was needed and I also did not need to include arm64_neon.h (arm_neon.h seems to work just fine).

Problem is... I have no way to test if it works. I don't own / know someone that has something that runs Windows on ARM and I don't know a place where you could rent a virtual machine either.

**Comment by amerkoleci** [comment] 2022-11-05 20:35
Same here, good job on making it work, probably someone with ARM64 will come and test it and report any issues.

Good job again, as always

**Comment by jrouwe** [comment] 2022-11-05 23:01
Managed to get Windows 11 running on my Raspberry Pi, looks like it is almost working:

![image](https://user-images.githubusercontent.com/1621693/200144519-3d359598-306e-465f-8d95-9df22ddaeb14.png)

(flushing denormals state doesn't get restored properly, that's also most likely the cause of the other test failures)

**Comment by jrouwe** [comment] 2022-11-06 12:34
Merged #317. All unit tests are now passing and even the sample app works on Raspberry Pi (at about 10fps, mostly due to rendering being really slow).

**Closed by jrouwe** 2022-11-06 12:34 UTC

**Comment by amerkoleci** [comment] 2022-11-06 13:37
> Merged #317. All unit tests are now passing and even the sample app works on Raspberry Pi (at about 10fps, mostly due to rendering being really slow).

Are you using d3d12 rendering on raspberry? Maybe we should consider opengl renderer as well, I can help

**Comment by jrouwe** [comment] 2022-11-06 15:07
Yes, it's running D3D12. I doubt that OpenGL will work better on the Pi since it has a very simple GPU that is not meant for 3D graphics. Actually, I'm amazed that it runs at all. As all the big companies seem to be abandoning OpenGL, I would be more interested in a Vulkan/Metal renderer so that the samples can run on Linux/Android/iOS/macOS.

**Comment by Wunkolo** [comment] 2022-11-06 18:23
I'll be getting a [ThinkPad x13s](https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpadx/thinkpad-x13s-(13-inch-snapdragon)/len101t0019) soon to possibly help with some testing. The SC8280XP in particular supports Windows On Arm and is getting some [official Linux support](https://lore.kernel.org/linux-arm-kernel/?q=SC8280XP) from [Lenovo](https://forums.lenovo.com/t5/Other-Linux-Discussions/Does-anybody-know-if-there-is-work-being-done-to-integrate-X13s-ARM-processor-with-linux/m-p/5175315).

Currently Windows on Arm does not support Vulkan due to the lack of drivers and only support DirectX. But it's worth keeping track of [dozen](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14766) to add to possibly the case of have a central Vulkan implementation that works on all platforms.

**Comment by jrouwe** [comment] 2022-11-06 18:44
Cool, let me know if it works!

**Comment by jrouwe** [comment] 2022-11-11 12:42
Thanks for testing, that's good news!

**Comment by amerkoleci** [comment] 2022-11-16 17:36
I'm not on PC right now, we need to remove the -g from here: https://github.com/jrouwe/JoltPhysics/blob/master/Build/CMakeLists.txt#L156
Right now I have ubuntu binary of 54mb

**Comment by jrouwe** [comment] 2022-11-16 20:51
In general it's quite handy to have the symbols available in every build for debugging purposes, so I don't want to blanket remove -g. What we do is create a build with symbols, save it somewhere in case we need to resolve a crash against it and then run ```strip <filename>``` to strip the symbols. Alternatively I can make it optional to generate symbols and then you would have to turn them off with something like ```cmake ... -DGENERATE_SYMBOLS=OFF```.

**Comment by amerkoleci** [comment] 2022-11-16 21:05
An option looks good for me, thanks!

**Comment by jrouwe** [comment] 2022-11-17 20:48
#337 adds ```-DGENERATE_DEBUG_SYMBOLS=OFF``` to disable. Note that it may be still a good idea to strip the dynamic library after compilation as that still seems to shrink it.
