### ISSUE TITLE
Character gets stuck in a complex mesh

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#364] opened 2022-12-18 13:39 UTC
This is another issue using CharacterVirtual (or maybe the same issue as https://github.com/jrouwe/JoltPhysics/issues/363)

I jump against a complicated mesh, and the character gets stuck in the air, but attached to the mesh.  I can't even move the character away from the mesh.
See
https://youtu.be/gAWmaogCLaw

Edit: it also happens in meshes with far fewer triangles.

**Comment by jankrassnigg** [comment] 2022-12-18 14:54
I have observed the same issue. This mesh is guaranteed to get a virtual character stuck:
https://polyhaven.com/a/GothicBed_01

**Comment by jrouwe** [comment] 2022-12-18 15:38
I will investigate.

**Comment by Ono-Sendai** [comment] 2022-12-18 16:19
Great, thanks.  
Let me know if you need any more details.
Model is from here: https://sketchfab.com/3d-models/aphrodite-of-milos-a-plaster-cast-db693358e0054ccf917bbe763455cd5e

**Comment by jrouwe** [comment] 2022-12-18 16:22
Can you export this mesh/scene using the same technique as in ```SamplesApp::TakeSnapshot()```? Otherwise I will need to create a mesh importer for blender first.

**Comment by Ono-Sendai** [comment] 2022-12-18 16:24
yup, will try tmrw.

**Comment by Ono-Sendai** [comment] 2022-12-19 02:03
Here you go: https://www.dropbox.com/s/ze14wd17wwl76um/jolt_snapshot_with_aphrodite.bin?dl=0
Note that I use z-up.

**Comment by jrouwe** [comment] 2022-12-19 21:31
I managed to load the file and reproduce the issue. 

The reason why it is failing is that the mesh is so detailed that it hits the maximum contact point limit (CharacterVirtualSettings::mMaxNumHits) which means any further contacts will be discarded. This causes it to miss some contacts which means you can move into geometry and if you move and the code then finds a different set of contacts you can get stuck inside. I tried running with mMaxNumHits = 65536 and then I couldn't reproduce the issue anymore. Unfortunately performance goes down the drain in that case.

My first advise would be: Physics geometry should really not be that detailed. Run the mesh through some mesh simplifier before feeding it to the physics system.

If that's not an option then I can investigate if I can make a smarter way of discarding contact points, but don't expect good performance with this triangle density (also not when you drop dynamic objects on the mesh).

**Comment by jankrassnigg** [comment] 2022-12-22 09:36
I was expecting that the complexity of the mesh is the key issue, that's also why I originally did not report this issue, because the mesh that I linked above shouldn't be used for collision, obviously. Still it is good to know what exactly the issue is, and that it indeed goes away when all contacts are dealt with.

I am wondering, whether ignoring contact points is the right solution, though. If I understand it correctly, once you exceed the limit, it will be extremely easy to get stuck, even just one contact point too many could trap the character and never let it out.

So I'm wondering whether it might be a better idea to just not move the character AT ALL, when this happens. Basically, if you move forwards and that would lead to too many contacts, cancel the move altogether. That may be annoying to players, because some geometry won't give you the expected sliding behavior, but at least they can still move into any other direction that's safe, and thus it won't be game breaking.

What do you think?

**Comment by jrouwe** [comment] 2022-12-22 18:08
Unfortunately that would make the character get stuck. The contacts are determined at the beginning of the step so once you detect that there are too many you can't safely move in any direction. Also the contacts could be caused by something that is moving towards the character.

I think the best solution would be to do contact point reduction by looking at positions and normals and discard similar normals/further points.

**Comment by jrouwe** [comment] 2022-12-28 23:09
I created a fix in #377

**Closed by jrouwe** 2022-12-28 23:09 UTC

**Comment by jankrassnigg** [comment] 2022-12-29 05:42
Awesome! Will give it a try soon.
