### ISSUE TITLE
Issue with character getting stuck against edges and objects

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#363] opened 2022-12-18 13:34 UTC
Hi,

Here's an issue using CharacterVirtual where the character, while flying through the air after jumping, gets stuck, in the sense that the horizontal velocity seems to get set to zero.

What happens sometimes - character gets stuck along the vertical edge of the cube:
https://youtu.be/6fN9j-1GOW0

What should happen:
https://youtu.be/GG8SJ9N3ebE

**Comment by jrouwe** [comment] 2022-12-18 18:50
Same question here: Can you export your scene with code similar to ```SamplesApp::TakeSnapshot```? I'm guessing this is not a simple box shape you're jumping against.

**Comment by Ono-Sendai** [comment] 2022-12-19 01:41
It is a simple box shape.

**Comment by jrouwe** [comment] 2022-12-19 21:34
I managed to repro this issue as well. The box is actually a MeshShape (not a BoxShape) and it looks like the wrong contact normals are selected but I don't have any more time tonight to debug.

**Comment by Ono-Sendai** [comment] 2022-12-20 02:12
Here's a video showing what is probably the same issue: https://www.youtube.com/watch?v=S_mekusjF7k
After walking into an object (and hence being immediately adjacent to it), jumping sometimes seems to hit something.
It only seems to happen on some sides of the object.

This is probably easier to replicate, since it doesn't involve launching yourself at some particular angle.

**Comment by jrouwe** [comment] 2022-12-21 22:06
For some reason I cannot reproduce that, jumping works fine for me (I'm using the default capsule from the CharacterVirtual test, you probably have different dimensions and perhaps a different shape). The thing I can 100% repro is moving along this box:

![image](https://user-images.githubusercontent.com/1621693/209010744-4fefee59-faa9-4c0d-8aa8-08524086af2d.png)

It collides (among other faces) with the edge of the marked face and then for some reason returns a normal that opposes movement so the character stops. I have to debug the collision detection code to see why this happens.

**Comment by jrouwe** [comment] 2022-12-31 10:02
Please test if my last fix fixes the issue for you as I wasn't able to reproduce all of your issues.

**Comment by Ono-Sendai** [comment] 2023-01-02 12:06
Cool.  Am on holiday, will try in a coupe of days.

**Comment by Ono-Sendai** [comment] 2023-01-04 23:20
Hi, no, it doesn't fix getting stuck along the edge of the box.

**Comment by jrouwe** [comment] 2023-01-06 11:48
Here's your scene and the CharacterVirtualTest updated to load that scene:

[Patch.zip](https://github.com/jrouwe/JoltPhysics/files/10359839/Patch.zip)

I've been trying again and indeed I can still get it to stop sliding (although it's much harder than before). I'll investigate again.

**Comment by Ono-Sendai** [comment] 2023-01-13 00:54
Have been messing around riding on frictionless objects, and am seeing some behaviour that seems like the same issue:

https://www.youtube.com/watch?v=lDa8r9FNC68

The red box is a box shape, the ground is a mesh shape.  The ground 'plane' is tesselated with ground mesh shapes, the boundary between them is along the x=0 and y=0 lines, which can be distinguished by looking at the RGB arrows that signify the world origin.   

As you can see the frictionless box object seems to stop sliding and 'hit' the boundaries between the quads.

**Comment by jrouwe** [comment] 2023-01-15 14:22
This looks like a different issue. How is the ground shape tessellated? Jolt keeps track of 'active edges' (edges that you can collide with), if your triangulated mesh has T-edges then they will become 'active' and will trigger what you're seeing here.

Illustration:

![image](https://user-images.githubusercontent.com/1621693/212546060-46bc098d-fc7f-418e-8e82-80021a67cea6.png)

The screenshot above comes from the 'General' / 'High Speed' Test with scene 'Convex Hull On Large Triangles' which is an example of a badly tessellated plane. The active edges can be rendered using MeshShape::sDrawTriangleOutlines.

**Comment by Ono-Sendai** [comment] 2023-01-16 01:05
I don't think there are any T edges within individual meshes, however the ground plane is tessellated with completely different bodies.

**Comment by jrouwe** [comment] 2023-01-16 19:27
That will result in the same thing. Edges from different bodies are not 'welded' (as it is called), so you can get ghost collisions from these edges. The best solution is to combine the floor in a single mesh. I may implement this in the future, but I have not needed it so far.

**Comment by jrouwe** [comment] 2023-01-20 17:02
Going back to the original problem of the character getting stuck against a vertical edge of a box:

This is caused by a floating point precision error in the collision detection functions which cause it to return a wrong normal. By increasing the tolerance in this location: 

https://github.com/jrouwe/JoltPhysics/blob/d5cf4634292ad9a35421ffceb42a50faf3ce5562/Jolt/Geometry/ClosestPoint.h#L174 

from 1.0e-13 to 1.0e-11 made it go away for me.

Can you try this out to see if this fixes the issue in your application as well?

**Comment by jrouwe** [comment] 2023-01-22 11:06
I did some further work on this and in the end I did not need to increase the tolerance.

Can you try #417 instead?

**Comment by Ono-Sendai** [comment] 2023-01-23 00:31
Still happens: https://www.youtube.com/watch?v=1rRX1rb09Yc

**Comment by Ono-Sendai** [comment] 2023-01-23 00:36
Still happens with bugfix/getclosest_tolerance branch.

**Comment by jrouwe** [comment] 2023-01-23 06:40
Can you apply Patch.zip that I posted earlier in this thread and adjust it to match the size/shape/speed of your character to make a repro in the Samples app? (I have tried but can't make it stick to an edge anymore)

**Comment by jrouwe** [comment] 2023-01-27 15:25
I've made an additional change to that PR and merged it into master (this fixes the same issue for an other user as reported in #419). Closing this as completed, if you are still having issues please provide an updated Patch.zip as described above and reopen the ticket.

**Comment by Ono-Sendai** [comment] 2023-02-01 23:08
Here's a patch that shows the problem:
[nickpatch.zip](https://github.com/jrouwe/JoltPhysics/files/10562747/nickpatch.zip)

The main change in the patch is to change the trajectory of the virtual character through the air to be a kind of ballistic trajectory - that is, mDesiredVelocity is not applied if the player is not supported, only gravity.  With this change, getting stuck on the edge becomes apparent.

See https://www.youtube.com/watch?v=ehF4X1UgRko for a recording.

**Comment by Ono-Sendai** [comment] 2023-02-02 01:44
Here's the related issue, which is an erroneous sideway velocity imparted when the player hits the cube after jumping towards it:

**Comment by jrouwe** [comment] 2023-02-02 20:59
I can reproduce the issue:

The first thing I notice is that you can accumulate a lot of speed. This may not happen in your own application but there is a difference between ```mCharacter->GetGroundState() == CharacterVirtual::EGroundState::OnGround``` and ```mCharacter->IsSupported()```, the second also returns true when you're on a steep slope. This means that on a steep slope you will continue to apply ```new_velocity += character_up_rotation * mDesiredVelocity;``` every frame leading to a very high horizontal velocity.

The problem of sticking against a wall is caused by ```mLinearVelocity = CancelVelocityTowardsSteepSlopes(desired_velocity);``` in ```CharacterVirtual::ExtendedUpdate``` resetting all horizontal velocity when you hit a wall under certain circumstances. The demo application sets the character velocity every frame, so you don't notice this happening, but you read the result and base your next frame on it so the character stops immediately. I need to debug this a bit further to come up with a proper fix.

**Comment by Ono-Sendai** [comment] 2023-02-02 22:36
> The problem of sticking against a wall is caused by `mLinearVelocity = CancelVelocityTowardsSteepSlopes(desired_velocity);` in `CharacterVirtual::ExtendedUpdate` resetting all horizontal velocity when you hit a wall under certain circumstances. The demo application sets the character velocity every frame, so you don't notice this happening, but you read the result and base your next frame on it so the character stops immediately. I need to debug this a bit further to come up with a proper fix.

Yes, this sounds like the problem.
The underlying issue seems to me that Jolt is somehow considering there to be a wall at the edge of the cube, that the player intersects with while sliding. (e.g. the side wall, not the one that the player has just jumped against).  What should rather happen is that either
a) the player doesn't not intersect with the side wall, or 
b) the player does intersect with the side wall, but you compute an effective normal based on the intersection which is the same as the wall the player is sliding against.  The side wall therefore has no additional effect.

At least this is how my player physics handled it, and it worked fine.

**Comment by jrouwe** [comment] 2023-02-03 20:56
Can you try 64fd3927e1df12f3b74243ac344bcb9b9e3233c7?

**Comment by Ono-Sendai** [comment] 2023-02-03 23:36
Hi Jorrit,
Thanks, that fixes the issue of getting stuck against the edge while jumping through the air.

However I am surprised that the character is even intersecting the side wall.  What I would expect to happen is that some epsilon keeps the character slightly off the wall the player jumped against, and then once velocity is zeroed out normal to that wall, the player should keep some small distance away from the wall.   Is this not the point of mCharacterPadding?   Or is that just used in some kind of relaxation phase?

The issue with jumping straight up being interrupted remains.  (https://github.com/jrouwe/JoltPhysics/issues/363#issuecomment-1358744852)

**Comment by Ono-Sendai** [comment] 2023-02-03 23:43
In fact in this video with your fix applied, you can see that the character, flying through the air without control input, is actually pushed away from the plane of the wall: https://youtu.be/yo6lSlXzqBQ

This indicates to me that that character was actually somewhat embedded in the wall, and hence the contact normal points back from the edge towards the character, instead of being the same as the front wall.  (Sorry maybe needs a diagram here).

Is this intentional behaviour?  It's not great because it gives a kind of elastic collision response to something that should ideally be completely inelastic (the character, at least according to computer game conventions)

**Comment by Ono-Sendai** [comment] 2023-02-03 23:45
To spell it out explicitly: If interpenetration with the front wall is avoided, then this kind of elastic collision will be avoided also.

**Comment by jrouwe** [comment] 2023-02-04 08:30
> However I am surprised that the character is even intersecting the side wall.

The reason why it's like that is that we have two-sided walls in the game, so we need to have collisions with back faces too. I think I can easily make that optional though.

> The issue with jumping straight up being interrupted remains. (https://github.com/jrouwe/JoltPhysics/issues/363#issuecomment-1358744852)

I cannot reproduce this with the patch you gave me. Can you?

> In fact in this video with your fix applied, you can see that the character, flying through the air without control input, is actually pushed away from the plane of the wall: https://youtu.be/yo6lSlXzqBQ

Yes, this is to be expected and actually caused by the character padding. Making the padding extremely big exaggerates this effect: 

![image](https://user-images.githubusercontent.com/1621693/216757106-00bb4fe6-7281-4dc2-b8de-cd542db18fda.png)

The character doesn't hit the edge yet, but the padding does. A 'future' contact point is found and its contact normal is pointing more towards the character than the wall normally would have. This forms a plane that is then used to slide the character against. By reducing the character padding you can lessen this effect at the cost of using extra CPU cycles (basically if you leave the character padding in 1 update you may have to do another full collision check). Note that in this case you can indeed argue that the back face should not collide at all, but the effect described above can happen for any collision.

**Comment by Ono-Sendai** [comment] 2023-02-04 08:42
> > The issue with jumping straight up being interrupted remains. ([#363 (comment)](https://github.com/jrouwe/JoltPhysics/issues/363#issuecomment-1358744852))
> 
> I cannot reproduce this with the patch you gave me. Can you?

I haven't replicated it exactly, but there is the behaviour mentioned here: https://github.com/jrouwe/JoltPhysics/issues/363#issuecomment-1413031536 (sideways velocity being imparted) which may stem from the same underlying problem.   Possibly there is some difference in player input velocity handling that results in the different behaviours.

**Comment by Ono-Sendai** [comment] 2023-02-04 08:56
> 
> ![image](https://user-images.githubusercontent.com/1621693/216757106-00bb4fe6-7281-4dc2-b8de-cd542db18fda.png)
> 
> The character doesn't hit the edge yet, but the padding does. A 'future' contact point is found and its contact normal is pointing more towards the character than the wall normally would have. This forms a plane that is then used to slide the character against. By reducing the character padding you can lessen this effect at the cost of using extra CPU cycles (basically if you leave the character padding in 1 update you may have to do another full collision check). Note that in this case you can indeed argue that the back face should not collide at all, but the effect described above can happen for any collision.

Well I'm not sure why your padding code works that way, but it doesn't seem great if it leads to unwanted results such as being pushed away from the wall.
This is more what I would expect:

![intersection](https://user-images.githubusercontent.com/30285/216758417-d190c80e-ec15-4ab9-b1db-a56a43296d40.png)

The sphere in this diagram may or may not intersect the side wall, due to floating point imprecision.  But if it does then it doesn't really matter because the contact normal should be nearly vertical.

**Comment by jrouwe** [comment] 2023-02-04 16:41
> Well I'm not sure why your padding code works that way

It works that way because it's cheaper and for most games you can control horizontal movement of the character in mid air so the artifacts that it causes are not noticeable (the image is greatly exaggerated). I said before that you can reduce the effect by reducing mCharacterPadding but I actually meant reducing mPredictiveContactDistance.

> but there is the behaviour mentioned here: https://github.com/jrouwe/JoltPhysics/issues/363#issuecomment-1413031536 (sideways velocity being imparted)

This the bug in the patched code you sent that I described:

> The first thing I notice is that you can accumulate a lot of speed. This may not happen in your own application but there is a difference between mCharacter->GetGroundState() == CharacterVirtual::EGroundState::OnGround and mCharacter->IsSupported(), the second also returns true when you're on a steep slope. This means that on a steep slope you will continue to apply new_velocity += character_up_rotation * mDesiredVelocity; every frame leading to a very high horizontal velocity.

If you fix the code like this the issue is gone:

```
	Vec3 new_velocity = mCharacter->GetLinearVelocity(); // NICK NEW - start with previous velocity
	if (mCharacter->GetGroundState() == CharacterVirtual::EGroundState::OnGround // If on ground
		&& (current_vertical_velocity.GetY() - ground_velocity.GetY()) < 0.1f) // And not moving away from ground
	{
		// Assume velocity of ground when on ground
		new_velocity = ground_velocity;

		// Jump
		if (inJump)
			new_velocity += cJumpSpeed * mCharacter->GetUp();

		new_velocity += character_up_rotation * mDesiredVelocity; ///<--- ADDED
	}
	//else
	//	new_velocity = current_vertical_velocity;  NICK NEW

	// Gravity
	new_velocity += (character_up_rotation * mPhysicsSystem->GetGravity()) * inDeltaTime;

	// Player input
	//if(mCharacter->IsSupported()) // NICK NEW - only apply desired velocity on ground.
	//	new_velocity += character_up_rotation * mDesiredVelocity; ///<--- REMOVED
```

**Comment by Ono-Sendai** [comment] 2023-02-05 02:46
> > Well I'm not sure why your padding code works that way
> 
> It works that way because it's cheaper and for most games you can control horizontal movement of the character in mid air so the artifacts that it causes are not noticeable (the image is greatly exaggerated). 

I would say most games have some horizontal inertia while jumping,

> > I said before that you can reduce the effect by reducing mCharacterPadding but I actually meant reducing mPredictiveContactDistance.

Weird stuff happens when mPredictiveContactDistance is set to 0 or a small value (e..g 1.e-4f).  The player gets stuck to edges and objects etc.




I added a line like this:

&& (current_vertical_velocity.GetY() - ground_velocity.GetY()) < 0.1f) // And not moving away from ground

to my code, and it fixes the jumping not working in some cases.  So I think it was the problem of IsSupported() still returning true after a jump had taken place.

**Closed** 2023-02-05 12:35 UTC

**Comment by jrouwe** [comment] 2023-02-05 12:38
> Weird stuff happens when mPredictiveContactDistance is set to 0

Yes, 0 or very close to 0 is too small. That will break the sliding ability of the character. I would say the minimum is about 1 cm.

In any case I added an option to turn on back face culling (CharacterVirtualSettings::mBackFaceMode) so you can now make it completely ignore backfacing triangles.

**Comment by Ono-Sendai** [comment] 2023-02-06 12:58
> In any case I added an option to turn on back face culling (CharacterVirtualSettings::mBackFaceMode) so you can now make it completely ignore backfacing triangles.

Thanks, I don't need this though.

**Comment by jrouwe** [comment] 2023-02-06 20:35
Why not? In my tests it fixes the being pushed away from the wall (https://www.youtube.com/watch?v=yo6lSlXzqBQ) issue completely.

**Comment by Ono-Sendai** [comment] 2023-02-06 23:58
I have single-face geometry I still need to collide with from both sides.
