### ISSUE TITLE
Jumping after walking against an object gets stuck

### ISSUE THREAD

**Issue by Ono-Sendai** [jrouwe/JoltPhysics#259] opened 2022-10-10 09:55 UTC
Hi there, I'm running into an issue with the CharacterVirtual physics.
I walk up to / against an object, and since the player model doesn't penetrate it, it ends up immediately adjacent to it.
Then I jump (set vertical velocity to some large value).  However a (spurious) contact point seems to be detected between the player model and the object.  It's maybe some kind of sliding contact, however it interrupts the jump, since when I query GetGroundState(), it reports that the player is on the ground. (EGroundState::OnGround).

You can see what happens in this video: https://www.youtube.com/watch?v=fMd3egnWvp4
In the video, the first two jumps are what should happen.  Then I move closer to the object, and the next jumps are interrupted.

Note that there are some pretty weird ground contacts reported, e.g. 1.27 metres off the ground, and with contact normal = (0,0,0).
Please note that I'm using +z up!

So I may be doing something wrong (the player movement code is complicated), but Jolt does seem to be doing something incorrectly.

**Comment by Ono-Sendai** [comment] 2022-10-10 10:22
Putting a breakpoint on the jump,

old_position = {mValue={m128_f32=0x0000007129fd7360 {-37.9305458, 5.48280048, -8.73987105e-08, -0.554962635} m128_u64=...} ...}

// jolt_character->Update() runs

new_position = {mValue={m128_f32=0x0000007129fd7510 {-37.9305458, 5.48280048, 0.0709071308, -0.484055400} m128_u64=...} ...}

velocity = {mValue={m128_f32=0x0000007129fd7540 {0.00000000, 0.00000000, 4.33971310, 4.33971405} m128_u64=0x0000007129fd7540 {...} ...} ...}

So the Update() function moves the player up by 7 cm, with an effective velocity of 4.3 m/s.
However after calling Update(), GetGroundState() still reports EGroundState::OnGround.

I guess this is the root of the problem.  I can work around this by considering the player off the ground until Update() has run again, even if GetGroundState() is reporting OnGround.

**Comment by jankrassnigg** [comment] 2022-10-10 12:05
I reported the same issue a couple of weeks ago and Jorrit fixed it a bit later. At least I didn't see it happen for me anymore. Are you using the latest version of Jolt? If not, try updating.

**Comment by jrouwe** [comment] 2022-10-10 20:08
Can you try #266? I can reproduce the normal being 0 but I don't get stuck.

**Comment by Ono-Sendai** [comment] 2022-10-11 01:38
I tried #266, maybe it fixes some stuff, but still have a problem.
See https://www.youtube.com/watch?v=YUF1fgGc1iI

Jolt is reporting that the player is OnGround, with a collision point at the top edge of the yellow block (2.4 metres above ground).   

Shouldn't contacts between the player body and other bodies only be counted if they are near the feet of the player?
Also the player body is not resting on this point in any sense.

**Comment by Ono-Sendai** [comment] 2022-10-11 01:41
The reason the player is getting stuck in the video above, btw, is that i'm zeroing out velocity in the surface normal direction when Jolt reports OnGround.

**Comment by jrouwe** [comment] 2022-10-11 19:52
I'm hoping you mean that you zero out the velocity in the surface normal direction when you're on STEEP ground?

Are you applying gravity after doing that? The character will not fall unless you apply gravity yourself, see CharacterVirtualTest::HandleInput:

```new_velocity += mPhysicsSystem->GetGravity() * inDeltaTime;```

which happens after the block:

```// Cancel movement in opposite direction of normal when sliding```

**Comment by jrouwe** [comment] 2022-10-21 22:11
Can you try #273 (has been merged into master)?

Make sure you set up CharacterVirtualSettings::mSupportingVolume (found in CharacterBaseSettings) as shown in CharacterVirtualTest::Initialize.

This should prevent Jolt from reporting On(Steep)Ground if you're jumping up against something (it will return NotSupported instead).

**Comment by Ono-Sendai** [comment] 2022-10-22 10:35
> I'm hoping you mean that you zero out the velocity in the surface normal direction when you're on STEEP ground?

No I was zeroing out the velocity in the normal direction when on any ground.    Isn't that what happens in real life? :)

Yes I am applying gravity after that.

**Comment by Ono-Sendai** [comment] 2022-10-22 10:36
> Can you try #273 (has been merged into master)?
> 
> Make sure you set up CharacterVirtualSettings::mSupportingVolume (found in CharacterBaseSettings) as shown in CharacterVirtualTest::Initialize.
> 
> This should prevent Jolt from reporting On(Steep)Ground if you're jumping up against something (it will return NotSupported instead).

Tried #273, still have same problems.  Will look into your mSupportingVolume suggestion.

**Comment by Ono-Sendai** [comment] 2022-10-22 10:47
Ok mSupportingVolume seems to help, though it looks like a bit of a hack to me, no offense.
Shouldn't the capsule just not detect edges it's sliding against as ground supporting contacts in the first place?  
I.e. if an edge of a surface is sliding against the vertical side of a capsule, that shouldn't be counted as the player being on the ground, right?   
Or is this functionality for climbing up ledges or something?

**Comment by jrouwe** [comment] 2022-10-22 14:22
No offense taken :)

The whole CharacterVirtual is kind of hacky and full of epsilons and tweaks. The problem is that it's not physics at all, it is a gameplay feature, and unfortunately gameplay is something everyone can have an opinion about and there is no universal 'correct' thing to do (does the character need to slide here? can I walk up this kind of surface? can I push this thing? etc.). 

W.r.t. to mSupportingVolume, this is actually one of the lesser hacky things. For shapes in general it's not very well defined what the 'side' is. For a capsule it is maybe easy, but you can throw any shape into the character (well anything that eventually consists of convex shapes). Therefore I need some way of defining what the 'bottom' of the character is so that I know which contacts can potentially support the character. Before I would look at the contact normals, but it's easy to get a contact on the side of the character that points up enough to consider it 'supporting' the character even though it's not.

**Comment by jrouwe** [comment] 2022-10-24 12:31
Do you need any further help? Can I close this ticket?

Note that there is now also CharacterVirtual::ExtendedUpdate that makes integration a bit simpler.

**Comment by Ono-Sendai** [comment] 2022-10-24 12:44
Hi,
Thanks for your help, yes, lets close this ticket.

**Closed** 2022-10-24 13:29 UTC
